### ISSUE TITLE
add tailwind to the project

### ISSUE THREAD

**Issue by eraygundogmus** [frontendship/website#1]
add tailwind to the project 
find color palette on figma and add it to the tailwind.config.js

**Comment by imhalid** [comment]
Can you assign me to this task?

**Comment by imhalid** [comment]
#6 I did the tailwind setup here

**Comment by frontendship2** [comment]
@imhalid Will you continue this task? I approved it but I think we need to add our design features to tailwind.config.js

**Comment by imhalid** [comment]
Yes, I will continue, I will make up for the shortcomings as soon as possible.

**Comment by imhalid** [comment]
I submitted the other changes in this #17 PR.

**Comment by frontendship2** [comment]
@imhalid I will close this issue, thank you for your contribute.
