### ISSUE TITLE
Develop GitHub Section and Card component

### ISSUE THREAD

**Issue by frontendship2** [frontendship/website#10]
<img width="742" alt="Screen Shot 2022-10-25 at 00 11 46" src="https://user-images.githubusercontent.com/114862694/197630250-a918eb1b-d024-41f8-864c-daac35da0836.png">

Expected folder structure: 

    .
    ├── ...
    ├── components                 
    │   ├── [ComponentName]         
    │       └── [ComponentName].tsx       
    │       └── [ComponentName].module.css                     
    └── ...

**Comment by burak-balci** [comment]
I want to undertake this task.
