### ISSUE TITLE
Develop Event Section 

### ISSUE THREAD

**Issue by frontendship2** [frontendship/website#11]
This task contains 4 component as: 
Event Section, 
Event Grid, 
Event Banner (bigger image),
Event Card 
<img width="732" alt="Screen Shot 2022-10-25 at 00 13 15" src="https://user-images.githubusercontent.com/114862694/197630507-3c08c995-dd59-470c-ab64-b4b34cabb977.png">

Expected folder structure: 

    .
    ├── ...
    ├── components                 
    │   ├── [ComponentName]         
    │       └── [ComponentName].tsx       
    │       └── [ComponentName].module.css                     
    └── ...

**Comment by bsrakts** [comment]
🙋🏼‍♀️

**Comment by berktugates** [comment]
Büşra ile konuştuk bu taski beraber yapabilir miyiz?

**Comment by frontendship2** [comment]
> Büşra ile konuştuk bu taski beraber yapabilir miyiz?

Ofc. Issue assigned both of you

**Comment by furkananter** [comment]
We've spoken to each other and I've decided to get involved in that assignment if there is no problem.

**Comment by eraygundogmus** [comment]
@furkananter Ofc!
