### ISSUE TITLE
Develop Contributors Section & Card

### ISSUE THREAD

**Issue by frontendship2** [frontendship/website#12]
<img width="740" alt="Screen Shot 2022-10-25 at 00 13 40" src="https://user-images.githubusercontent.com/114862694/197630587-2de356e3-79c8-4f8e-832d-2b4a161190cf.png">

Expected folder structure: 

    .
    ├── ...
    ├── components                 
    │   ├── [ComponentName]         
    │       └── [ComponentName].tsx       
    │       └── [ComponentName].module.css                     
    └── ...

**Comment by veyselkartalmis** [comment]
Is this a swiper?

**Comment by frontendship2** [comment]
No, it is not.
