### ISSUE TITLE
We have yarn.lock in repo but also .gitignore

### ISSUE THREAD

**Issue by OrhanOzkercin** [frontendship/website#18]
We pushed the yarn.lock file to the repo but also added to the .gitignore file. 
As far as I know, there are some different ideas about this issue. I think adding a lock file is better because some changes in libraries could create some problems. Also, big projects are adding a lock file.

Examples:
https://github.com/facebook/react
https://github.com/vuejs/vue
https://github.com/facebook/create-react-app
https://github.com/mui/material-ui

**Comment by frontendship2** [comment]
Hello @OrhanOzkercin, can you open a pr for this?

**Comment by OrhanOzkercin** [comment]
Of course! I just wanted to discuss what we want. If it is okay, I can remove the .lock file from the . gitignore

**Comment by frontendship2** [comment]
> Of course! I just wanted to discuss what we want. If it is okay, I can remove the .lock file from the . gitignore

Ofc!

**Comment by eraygundogmus** [comment]
@OrhanOzkercin could you please update this issue's status?
