### ISSUE TITLE
feat: add path aliases

### ISSUE THREAD

**Issue by salihdev0** [frontendship/website#21]
We are just at the beginning of the project, but as the folders get deeper, our imports will get ugly.

For example, if we go a little further with the current config, an image like this is not even internal:

```tsx
import Header from "../../../components/Header/Header"
import Title from "../../../components/Title/Title"
```

If we add path aliases, we will get a nicer image as below:

```tsx
import Header from "components/Header/Header"
import Title from "components/Title/Title"
```

If you assign it to me I can fix it quickly.

**Comment by eraygundogmus** [comment]
Hey, it's a good idea. But we planned that we will develop this project for educational purposes too. Could you explain other community members in a voice chat?

**Comment by salihdev0** [comment]
Thanks for the feedback. I will try to explain it on discord at a suitable time.

**Comment by harundogdu** [comment]
```jsx
import Header from "components/Header/Header"
import Title from "components/Title/Title"
```
Under the same folder, horizontal architecture can also be preferred instead of vertical architecture.

```jsx
import {Header, Title, ...} from 'components'
```

**Comment by salihdev0** [comment]
İt can be used

there will be a tutorial on discord tomorrow on this topic. I can talk about it if you want.
@eraygundogmus

**Comment by eraygundogmus** [comment]
@harundogdu Great idea! Thanks for contributing. 
@ssibrahimbas It's on you. No worries

**Comment by eraygundogmus** [comment]
Thank you for contribution
