### ISSUE TITLE
upgrading to the next.js latest version

### ISSUE THREAD

**Issue by fdemir** [frontendship/website#28]
may we consider upgrading the project to the latest version next.js?  migration process well-defined the original documentation of next.js. we can benefit from the new features:

- nested layouts - new routing
- server components
- fast builds?

also, we can experiment with the new bundler(turbopack) if possible.

**Comment by eraygundogmus** [comment]
do you want to self-assign this issue?

**Comment by eraygundogmus** [comment]
I closed this issue due to Next 13 alpha bugs.
