### ISSUE TITLE
bug: restrict level prop of title component

### ISSUE THREAD

**Issue by salihdev0** [frontendship/website#31]
Currently our `TitleProps` accept all numbers for the level field. It should only take between 1 and 6 for HTML Header element (h1-h6).

So right now there is a check like below:

```ts
export type TitleProps = {
    level?: number;
    styles?: StyleTypes;
    children: React.ReactNode;
}
```

Then something like the following will work:

```tsx
<Title level={100}>My Title</Title> { /* rendered: <h100>My Title</h100> */ }
```

We must limit this field. I can easily do it with TypeScript

like this:

```ts

type HTMLTitleLevel = 1 | 2 | 3 | 4 | 5 | 6;

export type TitleProps = {
    level?: HTMLTitleLevel;
    styles?: StyleTypes;
    children: React.ReactNode;
}
```

**Comment by eraygundogmus** [comment]
I can assign this issue to you

**Comment by salihdev0** [comment]
I thought you assigned it to me and I sent pr :( 

still the problem is solved
