### ISSUE TITLE
bug: title component's styles are not working

### ISSUE THREAD

**Issue by salihdev0** [frontendship/website#49]
A small point was overlooked while getting the default style in the Title component, so the default styles are not coming.

![Screenshot 2022-11-06 at 11 37 43](https://user-images.githubusercontent.com/76786120/200161901-c69807f0-c84b-43be-aed3-8c2a661be923.png)

Initially, if there is no prop named level, it is set to 1. There is no problem here. However, if styles are not found in props, props.level is searched in ModuleStyles as default style. An error occurs here when props.level is undefined.

If we write the code in the image as below, there is no problem.

```tsx
const { level = 1, styles: propsStyles = ModuleStyles[`title-${level}`] } = props;
```

**Comment by eraygundogmus** [comment]
Hello @ssibrahimbas 
You've been great on this project since it's started. You are a maintainer now. You can review pull requests, assign issues and help us develop this project.
Thank you.

**Comment by salihdev0** [comment]
Thank you for your role and trust, I will deal with it in more detail after work.
