### ISSUE TITLE
Develop header component 

### ISSUE THREAD

**Issue by frontendship2** [frontendship/website#7]
<img width="931" alt="Screen Shot 2022-10-25 at 00 08 48" src="https://user-images.githubusercontent.com/114862694/197629768-8c069787-7409-44b7-a26e-2f514b816192.png">

Expected folder structure: 

    .
    ├── ...
    ├── components                 
    │   ├── [ComponentName]         
    │       └── [ComponentName].tsx       
    │       └── [ComponentName].module.css                     
    └── ...

**Comment by sedaklnc** [comment]
Can I do this task?

**Comment by eraygundogmus** [comment]
@sedaklnc Ofc. Thank you for your contributing
