### ISSUE TITLE
Develop Banner component

### ISSUE THREAD

**Issue by frontendship2** [frontendship/website#8]
<img width="576" alt="Screen Shot 2022-10-25 at 00 09 39" src="https://user-images.githubusercontent.com/114862694/197629892-cc9f2c3b-00c4-4c4d-a054-79947c0b4916.png">

Expected folder structure: 

    .
    ├── ...
    ├── components                 
    │   ├── [ComponentName]         
    │       └── [ComponentName].tsx       
    │       └── [ComponentName].module.css                     
    └── ...

**Comment by imhalid** [comment]
@muhammed-gumus and I want to do this task.

**Comment by muhammed-gumus** [comment]
I want this task:)
