### ISSUE TITLE
Develop Brief Section and Card component

### ISSUE THREAD

**Issue by frontendship2** [frontendship/website#9]
<img width="752" alt="Screen Shot 2022-10-25 at 00 11 15" src="https://user-images.githubusercontent.com/114862694/197630171-cb97fd81-f625-4092-a0d2-2b478dfeb3d2.png">

Expected folder structure: 

    .
    ├── ...
    ├── components                 
    │   ├── [ComponentName]         
    │       └── [ComponentName].tsx       
    │       └── [ComponentName].module.css                     
    └── ...

**Comment by altankurt** [comment]
@birkaany and me take it if it's convenient.

**Comment by birkaany** [comment]
I can help with this too

**Comment by frontendship2** [comment]
Great! Thanks for contributions.

**Comment by altankurt** [comment]
Ben yanlışlıkla assignment  yaptım kendimi. Tekrar atayabilir misin @eraygundogmus ?
